USE cms;

DROP TABLE IF EXISTS pharmacy;
CREATE TABLE IF NOT EXISTS pharmacy (
    DESYNPUF_ID TEXT,
    PDE_ID TEXT,
    SRVC_DT DATE,
    PROD_SRVC_ID TEXT,
    QTY_DSPNSD_NUM FLOAT,
    DAYS_SUPLY_NUM FLOAT,
    PTNT_PAY_AMT FLOAT,
    TOT_RX_CST_AMT FLOAT
);

